server:
  port: 6666
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: "http://localhost:9001/eureka"
spring:
  application:
    name: "Common"
  redis:
    host: 127.0.0.1
    port: 3306
    database: 0
    password: 1
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100

feign:
  hystrix:
    enabled: true