server:
  port: 9004
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: "http://localhost:9001/eureka"
spring:
  application:
    name: "Hystrix"
feign:
  hystrix:
    enabled: true